import uuid
from sqlalchemy import Column, String, Numeric, Date, ForeignKey, CheckConstraint, text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from .types import TIMESTAMPTZ
from sqlalchemy.orm import relationship

from .base import Base
from .enums import PayrollPeriodStatus, SessionTypeType
from .mixins import CreatedAtMixin


class PayrollPeriod(Base, CreatedAtMixin):
    __tablename__ = "payroll_periods"

    id                   = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"), default=uuid.uuid4)
    label                = Column(String(64), nullable=False)
    start_date           = Column(Date, nullable=False)
    end_date             = Column(Date, nullable=False)
    currency             = Column(String(3), nullable=False)
    status               = Column(PayrollPeriodStatus, nullable=False)
    approved_by          = Column(UUID(as_uuid=True), ForeignKey("admin_users.id"), nullable=True)
    export_generated_at  = Column(TIMESTAMPTZ, nullable=True)

    # Relationships
    approver   = relationship("AdminUser",       back_populates="approved_payroll", foreign_keys=[approved_by])
    sessions   = relationship("Session",         back_populates="payroll_period")
    line_items = relationship("PayrollLineItem", back_populates="payroll_period")


class PayrollLineItem(Base, CreatedAtMixin):
    """
    Per-worker, per-session payroll calculation output.
    Exception flags are auto-generated by the payroll engine for:
      - missing required fields
      - force_released session without reason
      - hours deviation from shift
      - percentages not summing to 100%
    """
    __tablename__ = "payroll_line_items"
    __table_args__ = (
        CheckConstraint(
            "worker_pct + gs_pct + partner_pct = 100.00",
            name="ck_payroll_line_items_splits_sum",
        ),
    )

    id                = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"), default=uuid.uuid4)
    payroll_period_id = Column(UUID(as_uuid=True), ForeignKey("payroll_periods.id"), nullable=False, index=True)
    session_id        = Column(UUID(as_uuid=True), ForeignKey("sessions.id"),        nullable=False)
    worker_id         = Column(UUID(as_uuid=True), ForeignKey("workers.id"),         nullable=False, index=True)
    session_type      = Column(SessionTypeType, nullable=False)
    gross_amount      = Column(Numeric(12, 2), nullable=False)
    worker_pct        = Column(Numeric(5, 2),  nullable=False)
    gs_pct            = Column(Numeric(5, 2),  nullable=False)
    partner_pct       = Column(Numeric(5, 2),  nullable=False)
    worker_net        = Column(Numeric(12, 2), nullable=False)
    gs_net            = Column(Numeric(12, 2), nullable=False)
    partner_net       = Column(Numeric(12, 2), nullable=False)
    exception_flags   = Column(JSONB, nullable=False, server_default="'[]'")

    # Relationships
    payroll_period = relationship("PayrollPeriod", back_populates="line_items")
    session        = relationship("Session",       back_populates="payroll_line_items")
    worker         = relationship("Worker",        back_populates="payroll_line_items")
