"""Split the combined root .env.local into backend/.env and frontend/.env.local.

Neither app reads the repo-root file: Next.js only loads env files from
frontend/, and pydantic-settings resolves env_file=".env" against the backend's
working directory. This script partitions the combined file into the two
locations that are actually read.

Routing rules
-------------
  NEXT_PUBLIC_*            -> frontend only   (inlined into the browser bundle)
  SESSION_COOKIE_SECRET    -> BOTH            (shared HMAC secret)
  OTP_PEPPER               -> BOTH            (shared HMAC secret)
  everything else          -> backend only

SESSION_COOKIE_SECRET and OTP_PEPPER go to both because the backend signs the
session cookie (core/session_cookie.py) and the Next.js middleware verifies it
(middleware.ts:28-29, lib/auth/session-cookie.ts:8-9). The values must match or
every authenticated request bounces. They are NOT NEXT_PUBLIC_-prefixed, so
Next.js keeps them server-side and they never reach the browser.

Usage
-----
    python scripts/split-env.py            # refuses to clobber existing files
    python scripts/split-env.py --force    # overwrite
    python scripts/split-env.py --dry-run  # show routing, write nothing

Values are never printed — only key names.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / ".env.local"
BACKEND_OUT = ROOT / "backend" / ".env"
FRONTEND_OUT = ROOT / "frontend" / ".env.local"

SHARED = {"SESSION_COOKIE_SECRET", "OTP_PEPPER"}

REQUIRED_BACKEND = ["DATABASE_URL"]
REQUIRED_FRONTEND = [
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    "NEXT_PUBLIC_API_URL",
]


def parse(path: Path) -> list[tuple[str, str]]:
    """Return [(key, raw_value)] preserving original value text verbatim."""
    pairs: list[tuple[str, str]] = []
    for lineno, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):].lstrip()
        if "=" not in line:
            print(f"  ! line {lineno}: no '=', skipped", file=sys.stderr)
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key:
            continue
        pairs.append((key, value.strip()))
    return pairs


def render(pairs: list[tuple[str, str]], title: str) -> str:
    body = "\n".join(f"{k}={v}" for k, v in pairs)
    return (
        f"# {title}\n"
        f"# Generated by scripts/split-env.py from the combined root .env.local.\n"
        f"# Edit this file directly from now on; re-running the script overwrites it.\n\n"
        f"{body}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="overwrite existing files")
    ap.add_argument("--dry-run", action="store_true", help="show routing, write nothing")
    args = ap.parse_args()

    if not SOURCE.is_file():
        print(f"ERROR: {SOURCE} not found", file=sys.stderr)
        return 1

    pairs = parse(SOURCE)
    if not pairs:
        print(f"ERROR: no KEY=VALUE lines parsed from {SOURCE.name}", file=sys.stderr)
        return 1

    backend: list[tuple[str, str]] = []
    frontend: list[tuple[str, str]] = []
    for key, value in pairs:
        if key.startswith("NEXT_PUBLIC_"):
            frontend.append((key, value))
        elif key in SHARED:
            backend.append((key, value))
            frontend.append((key, value))
        else:
            backend.append((key, value))

    print(f"Parsed {len(pairs)} keys from {SOURCE.name}\n")
    print(f"backend/.env          ({len(backend)} keys)")
    for k, _ in backend:
        print(f"    {k}{'   [shared]' if k in SHARED else ''}")
    print(f"\nfrontend/.env.local   ({len(frontend)} keys)")
    for k, _ in frontend:
        if k in SHARED:
            tag = "   [shared, server-side only]"
        elif k.startswith("NEXT_PUBLIC_"):
            tag = "   [public — shipped to browsers]"
        else:
            tag = ""
        print(f"    {k}{tag}")

    missing_b = [k for k in REQUIRED_BACKEND if k not in {k for k, _ in backend}]
    missing_f = [k for k in REQUIRED_FRONTEND if k not in {k for k, _ in frontend}]
    if missing_b or missing_f:
        print("\n--- MISSING REQUIRED KEYS ---")
        for k in missing_b:
            print(f"    backend/.env         {k}")
        for k in missing_f:
            print(f"    frontend/.env.local  {k}")
        print("The apps will not start correctly until these are present.")

    if args.dry_run:
        print("\nDry run — nothing written.")
        return 0

    targets = [
        (BACKEND_OUT, render(backend, "Backend (FastAPI + Alembic) environment")),
        (FRONTEND_OUT, render(frontend, "Frontend (Next.js) environment")),
    ]
    existing = [p for p, _ in targets if p.exists()]
    if existing and not args.force:
        print("\nRefusing to overwrite:", file=sys.stderr)
        for p in existing:
            print(f"    {p.relative_to(ROOT)}", file=sys.stderr)
        print("Re-run with --force if that is what you want.", file=sys.stderr)
        return 1

    print()
    for path, text in targets:
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}  ({len(text.splitlines())} lines)")

    print("\nBoth files are already covered by .gitignore.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
