"""Restore partner_entities.created_at to timestamptz.

The model declares a Python datetime, but an earlier autogenerated migration
(f0572adde1a0) demoted the column to DATE, silently truncating timestamps.

Revision ID: a7b8c9d0e1f2
Revises: e4a9c1d2b3f4
Create Date: 2026-07-17
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a7b8c9d0e1f2'
down_revision: Union[str, None] = 'e4a9c1d2b3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'partner_entities', 'created_at',
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )


def downgrade() -> None:
    op.alter_column(
        'partner_entities', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
