export type Portal = 'public' | 'worker' | 'admin' | 'leadership' | 'audit';
export type PageStatus = 'live' | 'prototype';

export interface PageEntry {
  id: string;
  title: string;
  href: string;
  portal: Portal;
  purpose: string;
  features: string[];
  status: PageStatus;
  roles: string[];
}

export const PORTAL_LABELS: Record<Portal, string> = {
  public: 'Public',
  worker: 'Worker Portal',
  admin: 'Admin & Operations',
  leadership: 'Leadership Portal',
  audit: 'Audit & Security',
};

export const PAGES: PageEntry[] = [
  {
    id: 'landing',
    title: 'Landing Page',
    href: '/',
    portal: 'public',
    purpose: 'Explain the platform and provide login / access entry points.',
    features: ['Hero section', 'Statistics cards', 'Feature highlights', 'Platform preview', 'Login & Request Access CTAs'],
    status: 'live',
    roles: ['All visitors'],
  },
  {
    id: 'login',
    title: 'Login',
    href: '/login',
    portal: 'public',
    purpose: 'Authenticate workers, handlers, and leadership via Firebase Auth.',
    features: ['Email & password', 'Remember me', 'Forgot password', 'SSO-ready layout'],
    status: 'live',
    roles: ['All authenticated users'],
  },
  {
    id: 'reset-password',
    title: 'Reset Password',
    href: '/reset-password',
    portal: 'public',
    purpose: 'Simple password recovery workflow for locked-out users.',
    features: ['Email submission', 'Recovery confirmation', 'Return to login'],
    status: 'live',
    roles: ['All authenticated users'],
  },
  {
    id: 'worker-dashboard',
    title: 'Worker Dashboard',
    href: '/worker/dashboard',
    portal: 'worker',
    purpose: 'Worker home screen with metrics, shifts, sessions, and quick actions.',
    features: ['Active rank & quality score', 'Upcoming shifts', 'Recent sessions', 'Leaderboard preview', 'Quick actions'],
    status: 'live',
    roles: ['Worker', 'Partner Worker'],
  },
  {
    id: 'rdp-claim-board',
    title: 'RDP Claim Board',
    href: '/worker/rdp-claim-board',
    portal: 'worker',
    purpose: 'Real-time machine grid for claiming GlobalSolutions RDP resources.',
    features: ['Machine status grid', 'Country/client/status filters', 'Search', 'Claim action', 'Firebase live updates'],
    status: 'live',
    roles: ['Worker', 'Partner Worker'],
  },
  {
    id: 'active-session',
    title: 'Active Session Screen',
    href: '/worker/active-session',
    portal: 'worker',
    purpose: 'Live session view when a worker is actively working on an RDP machine.',
    features: ['Session timer', 'Machine details', 'Connection & heartbeat status', 'End session'],
    status: 'live',
    roles: ['Worker'],
  },
  {
    id: 'session-history',
    title: 'Session History',
    href: '/worker/session-history',
    portal: 'worker',
    purpose: 'Historical log of all worker sessions across RDP and external channels.',
    features: ['Date/machine/duration table', 'Status & type filters', 'CSV export'],
    status: 'live',
    roles: ['Worker', 'Partner Worker'],
  },
  {
    id: 'external-session',
    title: 'External Session Logging',
    href: '/worker/external-session',
    portal: 'worker',
    purpose: 'Log partner multilog and third-party platform sessions (Outlier, Handshake, Prolific).',
    features: ['Session type selector', 'Partner channel', 'Platform & reference ID', 'Duration & notes', 'Submit'],
    status: 'live',
    roles: ['Worker', 'Partner Worker'],
  },
  {
    id: 'assessment-center',
    title: 'Assessment Center',
    href: '/worker/assessments',
    portal: 'worker',
    purpose: 'MCQ assessments that feed 50% of the composite quality score.',
    features: ['Assigned tests', 'Completed tests', 'Scores', 'Certificates'],
    status: 'live',
    roles: ['Worker', 'Partner Worker'],
  },
  {
    id: 'leaderboard',
    title: 'Leaderboard',
    href: '/worker/leaderboard',
    portal: 'worker',
    purpose: 'Global and country rankings powered by composite quality scores.',
    features: ['Global & country filters', 'Rank animation', 'Quality score', 'Consistency bonus', 'Session streak'],
    status: 'live',
    roles: ['Worker', 'Partner Worker'],
  },
  {
    id: 'admin-dashboard',
    title: 'Admin Dashboard',
    href: '/admin/dashboard',
    portal: 'admin',
    purpose: 'Operations command center for handlers and country managers.',
    features: ['Worker & session KPIs', 'Payroll status', 'System health', 'Live activity feed', 'Session trend charts'],
    status: 'live',
    roles: ['Handler', 'Operations Lead', 'Country Manager'],
  },
  {
    id: 'worker-management',
    title: 'Worker Management',
    href: '/admin/workers',
    portal: 'admin',
    purpose: 'Create, edit, and deactivate worker profiles with role and partner assignment.',
    features: ['Worker table', 'Create/edit worker', 'Role assignment', 'Partner linking', 'Deactivate'],
    status: 'live',
    roles: ['Handler', 'Operations Lead', 'Country Manager'],
  },
  {
    id: 'partner-management',
    title: 'Partner Management',
    href: '/admin/partners',
    portal: 'admin',
    purpose: 'Manage partner entities, split percentages, overrides, and revenue breakdown.',
    features: ['Partner list', 'Split percentages', 'Client overrides', 'Revenue breakdown'],
    status: 'live',
    roles: ['Handler', 'Operations Lead'],
  },
  {
    id: 'rdp-management',
    title: 'RDP Management',
    href: '/admin/rdp',
    portal: 'admin',
    purpose: 'Control all RDP machines — status, maintenance, lock, force release, health.',
    features: ['Machine inventory', 'Maintenance mode', 'Lock machine', 'Force release', 'Health monitoring'],
    status: 'live',
    roles: ['Handler', 'Operations Lead'],
  },
  {
    id: 'live-session-monitor',
    title: 'Live Session Monitor',
    href: '/admin/live-sessions',
    portal: 'admin',
    purpose: 'Real-time oversight of all active sessions with force-end capability.',
    features: ['Active session list', 'Search & filters', 'Session timeline', 'Force end', 'Audit view'],
    status: 'live',
    roles: ['Handler', 'Operations Lead', 'Country Manager'],
  },
  {
    id: 'quality-management',
    title: 'Quality Management',
    href: '/admin/quality',
    portal: 'admin',
    purpose: 'Input subjective quality ratings with mandatory reason notes.',
    features: ['Communication ratings', 'Organisation ratings', 'Reason notes', 'Rating history'],
    status: 'live',
    roles: ['Handler', 'Operations Lead'],
  },
  {
    id: 'assessment-builder',
    title: 'Assessment Builder',
    href: '/admin/assessments',
    portal: 'admin',
    purpose: 'Manage MCQ question bank, categories, assignments, and results.',
    features: ['Question bank', 'Categories', 'Difficulty levels', 'Assignments', 'Results'],
    status: 'live',
    roles: ['Handler', 'Operations Lead'],
  },
  {
    id: 'payroll-dashboard',
    title: 'Payroll Dashboard',
    href: '/admin/payroll',
    portal: 'admin',
    purpose: 'Overview of current payroll period, pending reviews, and exception alerts.',
    features: ['Current period', 'Pending reviews', 'Exception alerts', 'Total payroll'],
    status: 'live',
    roles: ['Handler', 'Operations Lead', 'CEO'],
  },
  {
    id: 'payroll-calculation',
    title: 'Payroll Calculation View',
    href: '/admin/payroll/calculate',
    portal: 'admin',
    purpose: 'Per-worker earnings with partner splits, GS revenue, flags, and approval status.',
    features: ['Worker earnings', 'Partner splits', 'GS revenue', 'Exception flags', 'Approval workflow'],
    status: 'live',
    roles: ['Handler', 'Operations Lead', 'CEO'],
  },
  {
    id: 'payroll-export',
    title: 'Payroll Export',
    href: '/admin/payroll/export',
    portal: 'admin',
    purpose: 'Generate CSV/Excel payroll exports with period selector and approval logs.',
    features: ['CSV export', 'Excel export', 'Period selector', 'Approval logs'],
    status: 'live',
    roles: ['Handler', 'Operations Lead', 'CEO'],
  },
  {
    id: 'ceo-command',
    title: 'CEO Command Center',
    href: '/leadership/ceo-command',
    portal: 'leadership',
    purpose: 'Executive command view — the most impressive leadership dashboard.',
    features: ['KPI row', 'World map', 'Machine status', 'Partner performance', 'Revenue & payroll', 'Live feed'],
    status: 'live',
    roles: ['CEO', 'Leadership'],
  },
  {
    id: 'org-analytics',
    title: 'Organization Analytics',
    href: '/leadership/analytics',
    portal: 'leadership',
    purpose: 'Cross-dimensional analysis of country, partner, session, quality, and revenue data.',
    features: ['Country analysis', 'Partner analysis', 'Session analysis', 'Interactive charts'],
    status: 'live',
    roles: ['CEO', 'Leadership', 'Country Manager'],
  },
  {
    id: 'utilization',
    title: 'Utilization Dashboard',
    href: '/leadership/utilization',
    portal: 'leadership',
    purpose: 'RDP machine utilization, idle time, availability, and capacity forecasting.',
    features: ['Machine utilization', 'Idle vs active time', 'Availability %', 'Capacity forecast'],
    status: 'live',
    roles: ['CEO', 'Leadership', 'Operations Lead'],
  },
  {
    id: 'financial-intelligence',
    title: 'Financial Intelligence',
    href: '/leadership/financial',
    portal: 'leadership',
    purpose: 'Partner revenue, worker revenue, payroll costs, and profit trend analysis.',
    features: ['Partner revenue', 'Worker revenue', 'Payroll costs', 'Profit trends'],
    status: 'live',
    roles: ['CEO', 'Leadership'],
  },
  {
    id: 'audit-logs',
    title: 'Audit Logs',
    href: '/admin/audit-logs',
    portal: 'audit',
    purpose: 'Append-only audit trail of every material action in the system.',
    features: ['Actor & action', 'Entity & timestamp', 'Old/new values', 'Advanced filters'],
    status: 'live',
    roles: ['CEO', 'Operations Lead', 'Technical Admin'],
  },
  {
    id: 'system-settings',
    title: 'System Settings',
    href: '/admin/settings',
    portal: 'audit',
    purpose: 'Roles, permissions, feature toggles, integrations, and environment settings.',
    features: ['Roles & permissions', 'Feature toggles', 'Integrations', 'Environment config'],
    status: 'live',
    roles: ['Technical Admin', 'CEO'],
  },
  {
    id: 'notifications',
    title: 'Notification Center',
    href: '/admin/notifications',
    portal: 'audit',
    purpose: 'Central hub for payroll, machine, and quality alerts.',
    features: ['Payroll notifications', 'Machine alerts', 'Quality alerts', 'Mark read/unread'],
    status: 'live',
    roles: ['All authenticated users'],
  },
];

export function getPagesByPortal(portal: Portal): PageEntry[] {
  return PAGES.filter((p) => p.portal === portal);
}

export function getNavPagesForPortal(portal: Portal): PageEntry[] {
  return PAGES.filter((p) => p.portal === portal && p.id !== 'landing');
}
